In [2]:
import numpy as np

In [3]:
print("1d array")
a=np.array([1,2,3,4,5])
print(a)

1d array
[1 2 3 4 5]


In [4]:
print("2d array")
b=np.array([[1,2,3],[4,5,6]])
print(b)

2d array
[[1 2 3]
 [4 5 6]]
