In [1]:
import numpy as np

In [2]:
print("1d array")
a=np.array([1,2,3,4,5])
print(a)

1d array
[1 2 3 4 5]


In [ ]:
print("2d array")
b=np.array([[1,2,3],[4,5,6]])
print(b)

2d array
[[1 2 3]
 [4 5 6]]


In [4]:
print("2d array")
c=np.array([[1,2,9],[4,8,6]])
print(c)

2d array
[[1 2 9]
 [4 8 6]]


In [3]:
type(a)

numpy.ndarray